backend:
  name: github
  repo: your-username/hajj-pilgrim-guide
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Page Content", name: "body", widget: "markdown" }
      - label: "Locations"
        name: "locations"
        file: "locations.html"
        fields:
          - { label: "Page Content", name: "body", widget: "markdown" }

