backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - file: "index.html"
        label: "Homepage Text"
        name: "home"
        fields:
          - label: "Main Heading (EN)"
            name: "main_heading_en"
            widget: "string"
          - label: "Main Heading (UR)"
            name: "main_heading_ur"
            widget: "string"
          - label: "Main Heading (AR)"
            name: "main_heading_ar"
            widget: "string"
          - label: "Intro Text (EN)"
            name: "intro_en"
            widget: "text"
          - label: "Intro Text (UR)"
            name: "intro_ur"
            widget: "text"
          - label: "Intro Text (AR)"
            name: "intro_ar"
            widget: "text"
